### ISSUE TITLE
Error in requiriments.txt install command

### ISSUE THREAD

**Issue by jrodola** [Quantika14/osint-suite-tools#12]
Hi,

When launching "pip3 install -r requiriments.txt" I get this error:

```
~/osint-suite-tools$ pip3 install -r requiriments.txt
Collecting pydns
  Downloading pydns-2.3.6.tar.gz (28 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-k_wx2i6y/pydns_92b9dd2016cb4fe3b5d6a89b58758ea9/setup.py'"'"'; __file__='"'"'/tmp/pip-install-k_wx2i6y/pydns_92b9dd2016cb4fe3b5d6a89b58758ea9/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-falzbnmk
         cwd: /tmp/pip-install-k_wx2i6y/pydns_92b9dd2016cb4fe3b5d6a89b58758ea9/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-k_wx2i6y/pydns_92b9dd2016cb4fe3b5d6a89b58758ea9/setup.py", line 12, in <module>
        import DNS
      File "/tmp/pip-install-k_wx2i6y/pydns_92b9dd2016cb4fe3b5d6a89b58758ea9/DNS/__init__.py", line 14, in <module>
        import Type,Opcode,Status,Class
    ModuleNotFoundError: No module named 'Type'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/4b/9e/be4f6bbe72c2a12bb83f8a91e027fe58507afe7325dcd08b914f2bf0f1f0/pydns-2.3.6.tar.gz#sha256=f1960d8bff0aafad9252b9e80279748fe7ebe5e719487d132ccb1281523cdb62 (from https://pypi.org/simple/pydns/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Downloading pydns-2.3.4.tar.gz (24 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-k_wx2i6y/pydns_e3a7cd9ff06446ee81ac3ac4b866ba84/setup.py'"'"'; __file__='"'"'/tmp/pip-install-k_wx2i6y/pydns_e3a7cd9ff06446ee81ac3ac4b866ba84/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-53gzamym
         cwd: /tmp/pip-install-k_wx2i6y/pydns_e3a7cd9ff06446ee81ac3ac4b866ba84/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-k_wx2i6y/pydns_e3a7cd9ff06446ee81ac3ac4b866ba84/setup.py", line 12, in <module>
        import DNS
      File "/tmp/pip-install-k_wx2i6y/pydns_e3a7cd9ff06446ee81ac3ac4b866ba84/DNS/__init__.py", line 14, in <module>
        import Type,Opcode,Status,Class
    ModuleNotFoundError: No module named 'Type'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/38/f8/0fa679229b29dff07429214f64c11bab6627488a4976aadf49776aefe974/pydns-2.3.4.tar.gz#sha256=2d6ced52ad1e893d0ed6eca76b4b1eccdafbd76c54b41d2fa9cdaacd702853ea (from https://pypi.org/simple/pydns/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Downloading pydns-2.3.3.tar.gz (24 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-k_wx2i6y/pydns_6a993829f3e2475f85779ea6a8cd4e7b/setup.py'"'"'; __file__='"'"'/tmp/pip-install-k_wx2i6y/pydns_6a993829f3e2475f85779ea6a8cd4e7b/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-5run26yg
         cwd: /tmp/pip-install-k_wx2i6y/pydns_6a993829f3e2475f85779ea6a8cd4e7b/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-k_wx2i6y/pydns_6a993829f3e2475f85779ea6a8cd4e7b/setup.py", line 12, in <module>
        import DNS
      File "/tmp/pip-install-k_wx2i6y/pydns_6a993829f3e2475f85779ea6a8cd4e7b/DNS/__init__.py", line 14, in <module>
        import Type,Opcode,Status,Class
    ModuleNotFoundError: No module named 'Type'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/5b/3e/51dd1aa6a383df81360b8ec6f758e63ff7b75c4e3a520dfaf88727f9cbcb/pydns-2.3.3.tar.gz#sha256=6532f232928c858f2b9f1bf43bb56c63867d00417db72d00c380915570612d3a (from https://pypi.org/simple/pydns/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Downloading pydns-2.3.2.tar.gz (23 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-k_wx2i6y/pydns_819c39a50f05458a86cd322f7a0aa29f/setup.py'"'"'; __file__='"'"'/tmp/pip-install-k_wx2i6y/pydns_819c39a50f05458a86cd322f7a0aa29f/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-ajca1u0w
         cwd: /tmp/pip-install-k_wx2i6y/pydns_819c39a50f05458a86cd322f7a0aa29f/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-k_wx2i6y/pydns_819c39a50f05458a86cd322f7a0aa29f/setup.py", line 12, in <module>
        import DNS
      File "/tmp/pip-install-k_wx2i6y/pydns_819c39a50f05458a86cd322f7a0aa29f/DNS/__init__.py", line 14, in <module>
        import Type,Opcode,Status,Class
    ModuleNotFoundError: No module named 'Type'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/90/1e/99b6e6ca8da93e8eb48cfde7c9c8f174740f5c231790fa6185d014fbc5fd/pydns-2.3.2.tar.gz#sha256=377c85522d9dd41b6bf71f3ca7649712800ec920a69613a1b0c7caf455b85d8f (from https://pypi.org/simple/pydns/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement pydns
ERROR: No matching distribution found for pydns
```
Thanks

Javi

**Comment by AiAiWilly** [comment]
delete pydns from requirements.txt
