### ISSUE TITLE
error en buscador de telefonos

### ISSUE THREAD

**Issue by jukathaido** [Quantika14/osint-suite-tools#2]
Muy interesante la tool...

Pero en la parte de buscador de telefonos me da el siguiente error y no tengo narices de encontrar la solucion..si me podeis ayudar..
Traceback (most recent call last):
  File "BuscadorTelefonos.py", line 26, in <module>
    import requests, mechanize, re, twint
  File "/usr/local/lib/python3.8/site-packages/twint/__init__.py", line 14, in <module>
    from . import run
  File "/usr/local/lib/python3.8/site-packages/twint/run.py", line 4, in <module>
    from . import datelock, feed, get, output, verbose, storage
  File "/usr/local/lib/python3.8/site-packages/twint/get.py", line 15, in <module>
    from .output import Tweets, Users
  File "/usr/local/lib/python3.8/site-packages/twint/output.py", line 6, in <module>
    from .storage import db, elasticsearch, write, panda
  File "/usr/local/lib/python3.8/site-packages/twint/storage/db.py", line 1, in <module>
    import sqlite3
  File "/usr/local/lib/python3.8/sqlite3/__init__.py", line 23, in <module>
    from sqlite3.dbapi2 import *
  File "/usr/local/lib/python3.8/sqlite3/dbapi2.py", line 27, in <module>
    from _sqlite3 import *
ModuleNotFoundError: No module named '_sqlite3'

**Comment by Quantika14** [comment]
Hola, parece que te falta varias librerias de Twint, entre ellas sqlite3. 
Intenta tener todos los requisitos necesarios para TWINT: 
git clone https://github.com/twintproject/twint.git
cd twint
pip3 install . -r requirements.txt

**Comment by jukathaido** [comment]
Nada..sigue el mismo error. Me gustaría poder solucionarlo porque quiero mostrar la herramienta en un curso de Hacking ético y en un master de ciberinteligencia donde soy profesor. y la verdad..no encuentro donde puede estar el fallo...

**Comment by Quantika14** [comment]
El fallo es que no encuentra el módulo _sqlite3 de la libreria sqlite3, que utiliza la libreria Twint. Es un problema local que sale fuera de la aplicación de DG. Le recomendamos que pruebe en otra VM y reinstale los requisitos.

**Comment by jukathaido** [comment]
Solucionado. reinstale python3. Funciona perfecto.
Saludos y enhorabuena!!!!

**Comment by jukathaido** [comment]
Seria interesante que en el buscador de telefonos, usaseis waybackmachine, para ver moviles que han estado en alguna web y ahora no están. Saludos
