### ISSUE TITLE
error

### ISSUE THREAD

**Issue by shanow7** [Quantika14/osint-suite-tools#3]
hi, I've problem with start

~/osint-suite-tools$ python3 BuscadorNick.py
Traceback (most recent call last):
  File "BuscadorNick.py", line 32, in <module>
    from validate_email import validate_email
ModuleNotFoundError: No module named 'validate_email'

~/email-osint-ripper$ python3 eo-ripper.py
Traceback (most recent call last):
  File "eo-ripper.py", line 11, in <module>
    from validate_email import validate_email
ModuleNotFoundError: No module named 'validate_email'

**Comment by Quantika14** [comment]
Hi, already solved!

**Comment by shanow7** [comment]
hi, BuscadorNick dosen't work

~/osint-suite-tools$ python3 BuscadorNick.py                                                                                                                                    
Traceback (most recent call last):
  File "BuscadorNick.py", line 32, in <module>
    from validate_email import validate_email
  File "/usr/local/lib/python3.7/dist-packages/validate_email/__init__.py", line 1, in <module>
    from .validate_email import validate_email, validate_email_or_fail  # NOQA
  File "/usr/local/lib/python3.7/dist-packages/validate_email/validate_email.py", line 4, in <module>
    from .domainlist_check import domainlist_check
  File "/usr/local/lib/python3.7/dist-packages/validate_email/domainlist_check.py", line 4, in <module>
    from filelock import FileLock
ModuleNotFoundError: No module named 'filelock'

where do I need to insert the api keys?
