### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by shanow7** [Quantika14/osint-suite-tools#6]
Traceback (most recent call last):
  File "/home/osint/osint-suite-tools/BuscadorPersonas.py", line 432, in <module>
    main()
  File "/home/osint/osint-suite-tools/BuscadorPersonas.py", line 429, in main
    menu()
  File "/home/osint/osint-suite-tools/BuscadorPersonas.py", line 356, in menu
    search_indultoBOE(target_no_clean)
  File "/home/osint/osint-suite-tools/BuscadorPersonas.py", line 311, in search_indultoBOE
    DB.find_in_BOE(target)
  File "/home/osint/osint-suite-tools/modules/mongo.py", line 122, in find_in_BOE
    for x in cursor:
  File "/home/osint/.local/lib/python3.9/site-packages/pymongo/cursor.py", line 1207, in next
    if len(self.__data) or self._refresh():
  File "/home/osint/.local/lib/python3.9/site-packages/pymongo/cursor.py", line 1100, in _refresh
    self.__session = self.__collection.database.client._ensure_session()
  File "/home/osint/.local/lib/python3.9/site-packages/pymongo/mongo_client.py", line 1816, in _ensure_session
    return self.__start_session(True, causal_consistency=False)
  File "/home/osint/.local/lib/python3.9/site-packages/pymongo/mongo_client.py", line 1766, in __start_session
    server_session = self._get_server_session()
  File "/home/osint/.local/lib/python3.9/site-packages/pymongo/mongo_client.py", line 1802, in _get_server_session
    return self._topology.get_server_session()
  File "/home/osint/.local/lib/python3.9/site-packages/pymongo/topology.py", line 485, in get_server_session
    self._select_servers_loop(
  File "/home/osint/.local/lib/python3.9/site-packages/pymongo/topology.py", line 215, in _select_servers_loop
    raise ServerSelectionTimeoutError(
pymongo.errors.ServerSelectionTimeoutError: localhost:27017: [Errno 111] Connection refused, Timeout: 30s, Topology Description: <TopologyDescription id: 5ff5b915dcbfd614be4a043c, topology_type: Single, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [Errno 111] Connection refused')>]>

can you help?

**Comment by jlareos** [comment]
Start the mongodb service
